# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib rdfhelper, .registration = TRUE
NULL

OxStore <- new.env(parent = emptyenv())

OxStore$new <- function() .Call(wrap__OxStore__new)

OxStore$insert <- function(subject, predicate, object) .Call(wrap__OxStore__insert, self, subject, predicate, object)

OxStore$ask <- function(query) .Call(wrap__OxStore__ask, self, query)

#' @export
`$.OxStore` <- function (self, name) { func <- OxStore[[name]]; environment(func) <- environment(); func }

#' @export
`[[.OxStore` <- `$.OxStore`

# nolint end
